---
title: "AULA1_RSTUDIO(MAEII)"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2025-08-29"
---

```{r - DADOS}
# 1 criar um objeto simples
# crie um objeto PIB_Brasil com o valor 2200 em bilhões de reais

PIB_Brasil <- 2200

# crie um objeto POP_Brasil com o valor de 210 em milhões de pessoas 

POP_Brasil <- 210

```

```{r - CalculoPC}
# Calcular PIB per Capita 

PIB_PC <- PIB_Brasil/POP_Brasil
PIB_PC

```
```{r DATAFRAME}
# Crie um vetor chamado países com 3 países

países <- c("Brasil", "Chile", "México")

# Crie um vetor chamado PIB para os valores fictícios de PIB para esses países(em bilhões)

pib <- c(2200, 350, 1800)

# Crie um vetor inflação com valores fictícios de inflação (%) para os mesmos países

inflacao <- c(6.5, 4.2, 5.1)

# Junte os vetores em um data frame chamado dados 

dados <- data.frame(país = países,
                    pib = pib,
                    inflacao = inflacao)

# Visualize o resultado
dados

```



